In [81]:
import numpy as np
import math

### Task1

In [84]:
x = math.cos(math.pi/2)
x

6.123233995736766e-17

### Task2

In [42]:

A = np.array([[4, 2], [1, 2]])
b = np.array([10.488, 7.119])

# Approximate solution
x_numerical = np.array([1, 3])

# Calculate the residual vector
residual = A @ x_numerical - b

# Calculate the backward error
backward_error = np.linalg.norm(residual)

# Calculate the true solution norm
true_solution = np.array([10.488, 7.119])
true_solution_norm = np.linalg.norm(true_solution)

forward_error = x_numerical -(np.linalg.inv(A) @ b)
forward_error = np.linalg.norm(forward_error)

print("Backward Error:", backward_error)
print("Forward Error:", forward_error)


Backward Error: 0.5022997113278083
Forward Error: 0.12301625908797563


### Task3

In [101]:
xi = np.array([1.0, 1.1, 1.3, 1.5, 1.9, 2.1])
yi = np.array([1.84, 1.96, 2.21, 2.45, 2.94, 3.18])

degree_2 = 2
degree_3 = 3

# Construct the matrix A and vector b for degree 2 polynomial
A2 = np.column_stack([np.ones_like(xi), xi, xi ** 2])
b2 = yi

# Construct the matrix A and vector b for degree 3 polynomial
A3 = np.column_stack([np.ones_like(xi), xi, xi ** 2, xi ** 3])
b3 = yi

# (SVD) for degree 2 polynomial
U2, S2, VT2 = np.linalg.svd(A2, full_matrices=False)
x2 = np.dot(VT2.T, np.dot(np.linalg.inv(np.diag(S2)), np.dot(U2.T, b2)))

# (SVD) for degree 3 polynomial
U3, S3, VT3 = np.linalg.svd(A3, full_matrices=False)
x3 = np.dot(VT3.T, np.dot(np.linalg.inv(np.diag(S3)), np.dot(U3.T, b3)))

p2 = np.poly1d(x2)
p3 = np.poly1d(x3)

# Calculate the least squares errors for degree 2 and degree 3
error2 = np.sum((A2 @ x2 - yi)** 2)
error3 = np.sum((A3 @ x3 - yi)** 2)

print("Coefficients for Degree 2 Polynomial:")
print(x2)
print("Least Squares Error for Degree 2 Polynomial:", error2)

print("\nCoefficients for Degree 3 Polynomial:")
print(x3)
print("Least Squares Error for Degree 3 Polynomial:", error3)


Coefficients for Degree 2 Polynomial:
[ 0.59658071  1.25329314 -0.01085343]
Least Squares Error for Degree 2 Polynomial: 1.8014842300555337e-05

Coefficients for Degree 3 Polynomial:
[ 0.62901928  1.1850098   0.03533252 -0.01004723]
Least Squares Error for Degree 3 Polynomial: 1.7407310952221137e-05


In [106]:
(A3 @ x3 - yi)** 2

array([4.70100186e-07, 3.64632940e-06, 8.00775566e-06, 4.50599575e-06,
       6.81744654e-07, 9.53853055e-08])

In [ ]:
np.linalg.norm(A3 @ x3 - yi)